package irrgarten.UI;

import irrgarten.Directions;
import irrgarten.GameState;
import java.awt.Font;


/**
 *
 * @author Juan Carlos Vílchez Sánchez
 */
public class GraphicalUI extends javax.swing.JFrame implements UI {

    private Cursors cursors;
    /**
     * Creates new form GraphicalUI
     */
    public GraphicalUI() {
        cursors = new Cursors(this, true);
        initComponents();
        Labyrinth.setFont(new Font("Monospaced", Font.PLAIN, 12));
        setVisible(true);
    }
    
    @Override
    public Directions nextMove(){
        Directions direction = cursors.getDirection();
        return direction;
    }
    
    @Override
    public void showGame(GameState gameState){
        TextCurrentPlayer.setText(String.valueOf(gameState.getCurrentPlayer()));
        TextWinner.setText(String.valueOf(gameState.getWinner()));
        Labyrinth.setText(gameState.getLabyrinthv());
        PlayerScreen.setText(gameState.getPlayers());
        MonsterScreen.setText(gameState.getMonsters());
        LogScreen.setText(gameState.getLog());
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Labyrinth = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        PlayerScreen = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        MonsterScreen = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        LogScreen = new javax.swing.JTextArea();
        LabelWinner = new javax.swing.JLabel();
        TextWinner = new java.awt.TextField();
        TextCurrentPlayer = new javax.swing.JTextField();
        LabelCurrentPlayer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelLabyrinth = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Labyrinth.setColumns(20);
        Labyrinth.setRows(5);
        jScrollPane1.setViewportView(Labyrinth);

        PlayerScreen.setColumns(20);
        PlayerScreen.setRows(5);
        jScrollPane2.setViewportView(PlayerScreen);

        MonsterScreen.setColumns(20);
        MonsterScreen.setRows(5);
        jScrollPane3.setViewportView(MonsterScreen);

        LogScreen.setColumns(20);
        LogScreen.setRows(5);
        jScrollPane4.setViewportView(LogScreen);

        LabelWinner.setText("Winner:");

        TextWinner.setText("textField1");
        TextWinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextWinnerActionPerformed(evt);
            }
        });

        TextCurrentPlayer.setText("jTextField1");
        TextCurrentPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCurrentPlayerActionPerformed(evt);
            }
        });

        LabelCurrentPlayer.setText("CurrentPlayer:");

        jLabel1.setText("Jugadores:");

        jLabel2.setText("Monstruos:");

        jLabel3.setText("Log:");

        LabelLabyrinth.setText("Laberinto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelCurrentPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(LabelWinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(LabelLabyrinth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextCurrentPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(TextWinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCurrentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCurrentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(LabelLabyrinth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(536, 536, 536))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(387, 387, 387))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextWinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextWinnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextWinnerActionPerformed

    private void TextCurrentPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCurrentPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCurrentPlayerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCurrentPlayer;
    private javax.swing.JLabel LabelLabyrinth;
    private javax.swing.JLabel LabelWinner;
    private javax.swing.JTextArea Labyrinth;
    private javax.swing.JTextArea LogScreen;
    private javax.swing.JTextArea MonsterScreen;
    private javax.swing.JTextArea PlayerScreen;
    private javax.swing.JTextField TextCurrentPlayer;
    private java.awt.TextField TextWinner;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
